name: movie_list_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  firebase: 
  firebase_core: 
  firebase_auth: 
  cupertino_icons: ^1.0.0
  google_sign_in:
  modal_progress_hud: ^0.1.3
  auto_size_text: ^2.1.0
  sqflite: ^1.3.0
  image_picker: 
  toggle_switch:
  uuid: 
  fluttertoast: 
  percent_indicator: 
  flutter_launcher_icons: 

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.jpg"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
      - family: Billabong
        fonts:
          - asset: assets/fonts/Billabong.ttf
  # assets:
  # - assets/images/

  
